# Generic entity terms that should not dominate partial entity matching
ENTITY_GENERIC_TOKENS = {
    # Weather descriptors
    "super",
    "typhoon",
    "tropical",
    "storm",
    "depression",
    "bagyo",
    "bagyong",
    # Political/titles
    "president",
    "vice",
    "senator",
    "mayor",
    "governor",
    "congressman",
    "minister",
    "secretary",
    "representative",
    # Business/organization descriptors
    "company",
    "corporation",
    "inc",
    "corp",
    "ltd",
    "llc",
    "foundation",
    "organization",
    # Geographic descriptors
    "city",
    "province",
    "municipality",
    "region",
    "district",
    "barangay",
    "island",
    "country",
    # General descriptors
    "new",
    "old",
    "national",
    "international",
    "global",
    "local",
    "federal",
    "state",
    "central",
    "general",
}
