"""add chunk content

Revision ID: e6c3540edf50
Revises: c3b6b38c89a0
Create Date: 2026-01-12 21:15:30.407133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e6c3540edf50'
down_revision: Union[str, Sequence[str], None] = 'c3b6b38c89a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_vectors', sa.Column('chunk_content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_vectors', 'chunk_content')
    # ### end Alembic commands ###
